'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace FrondEnd

    Partial Public Class frmMantenimientoFuncionario

        '''<summary>
        '''txtIdentif control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIdentif As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNombre control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNombre As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPrimerApellido control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrimerApellido As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSegundoApellido control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSegundoApellido As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtUsuario control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUsuario As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtClave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClave As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlEstado control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlEstado As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnAgregar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAgregar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnEliminar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEliminar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnModificar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnModificar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''gvFuncionario control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvFuncionario As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
