'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On
Partial Public Class frmRegistroCursos

        '''<summary>
        '''txtIDCurso control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIDCurso As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNombre control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNombre As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCreditos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCreditos As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCupoMin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCupoMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCupoMax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCupoMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNotaMin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotaMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlGrado control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlGrado As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlEstado control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlEstado As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtCosto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCosto As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txt_IDCarrera control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_IDCarrera As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnRegistar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnRegistar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''gvCursos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvCursos As Global.System.Web.UI.WebControls.GridView
End Class