'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace FrondEnd

    Partial Public Class frmMantenimientoEmpleado

        '''<summary>
        '''txtCarnet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCarnet As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtIdentif control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIdentif As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNombre control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNombre As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPrimerApellido control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrimerApellido As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSegundoApellido control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSegundoApellido As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCarrera control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCarrera As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProyecto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProyecto As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTelef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTelef As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCorreo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCorreo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlEstado control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlEstado As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnRegistar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnRegistar As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''gvCursos control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvCursos As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
